CREATE DATABASE IF NOT EXISTS airline;
USE airline;

CREATE TABLE IF NOT EXISTS flights (
    FL_DATE DATE,
    AIRLINE VARCHAR(10),
    AIRLINE_DOT VARCHAR(10),
    AIRLINE_CODE VARCHAR(10),
    DOT_CODE INT,
    FL_NUMBER INT,
    ORIGIN VARCHAR(10),
    ORIGIN_CITY VARCHAR(100),
    DEST VARCHAR(10),
    DEST_CITY VARCHAR(100),
    CRS_DEP_TIME INT,
    DEP_TIME FLOAT,
    DEP_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF FLOAT,
    WHEELS_ON FLOAT,
    TAXI_IN FLOAT,
    CRS_ARR_TIME INT,
    ARR_TIME FLOAT,
    ARR_DELAY FLOAT,
    CANCELLED BOOLEAN,
    CANCELLATION_CODE VARCHAR(5),
    DIVERTED BOOLEAN,
    CRS_ELAPSED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    DELAY_DUE_CARRIER FLOAT,
    DELAY_DUE_WEATHER FLOAT,
    DELAY_DUE_NAS FLOAT,
    DELAY_DUE_SECURITY FLOAT,
    DELAY_DUE_LATE_AIRCRAFT FLOAT
);




-- Top airlines by average arrival delay
SELECT AIRLINE, AVG(ARR_DELAY) AS avg_delay
FROM flights
GROUP BY AIRLINE
ORDER BY avg_delay DESC;

-- Flights most affected by weather
SELECT COUNT(*) AS weather_affected_flights
FROM flights
WHERE DELAY_DUE_WEATHER > 0;
